// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitdetail"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitgeneral"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitunsold"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/schema"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	profitdetailMixin := schema.ProfitDetail{}.Mixin()
	profitdetail.Policy = privacy.NewPolicies(profitdetailMixin[0], schema.ProfitDetail{})
	profitdetail.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := profitdetail.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	profitdetailMixinFields0 := profitdetailMixin[0].Fields()
	_ = profitdetailMixinFields0
	profitdetailFields := schema.ProfitDetail{}.Fields()
	_ = profitdetailFields
	// profitdetailDescCreatedAt is the schema descriptor for created_at field.
	profitdetailDescCreatedAt := profitdetailMixinFields0[0].Descriptor()
	// profitdetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	profitdetail.DefaultCreatedAt = profitdetailDescCreatedAt.Default.(func() uint32)
	// profitdetailDescUpdatedAt is the schema descriptor for updated_at field.
	profitdetailDescUpdatedAt := profitdetailMixinFields0[1].Descriptor()
	// profitdetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profitdetail.DefaultUpdatedAt = profitdetailDescUpdatedAt.Default.(func() uint32)
	// profitdetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profitdetail.UpdateDefaultUpdatedAt = profitdetailDescUpdatedAt.UpdateDefault.(func() uint32)
	// profitdetailDescDeletedAt is the schema descriptor for deleted_at field.
	profitdetailDescDeletedAt := profitdetailMixinFields0[2].Descriptor()
	// profitdetail.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	profitdetail.DefaultDeletedAt = profitdetailDescDeletedAt.Default.(func() uint32)
	// profitdetailDescGoodID is the schema descriptor for good_id field.
	profitdetailDescGoodID := profitdetailFields[1].Descriptor()
	// profitdetail.DefaultGoodID holds the default value on creation for the good_id field.
	profitdetail.DefaultGoodID = profitdetailDescGoodID.Default.(func() uuid.UUID)
	// profitdetailDescCoinTypeID is the schema descriptor for coin_type_id field.
	profitdetailDescCoinTypeID := profitdetailFields[2].Descriptor()
	// profitdetail.DefaultCoinTypeID holds the default value on creation for the coin_type_id field.
	profitdetail.DefaultCoinTypeID = profitdetailDescCoinTypeID.Default.(func() uuid.UUID)
	// profitdetailDescBenefitDate is the schema descriptor for benefit_date field.
	profitdetailDescBenefitDate := profitdetailFields[4].Descriptor()
	// profitdetail.DefaultBenefitDate holds the default value on creation for the benefit_date field.
	profitdetail.DefaultBenefitDate = profitdetailDescBenefitDate.Default.(uint32)
	// profitdetailDescID is the schema descriptor for id field.
	profitdetailDescID := profitdetailFields[0].Descriptor()
	// profitdetail.DefaultID holds the default value on creation for the id field.
	profitdetail.DefaultID = profitdetailDescID.Default.(func() uuid.UUID)
	profitgeneralMixin := schema.ProfitGeneral{}.Mixin()
	profitgeneral.Policy = privacy.NewPolicies(profitgeneralMixin[0], schema.ProfitGeneral{})
	profitgeneral.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := profitgeneral.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	profitgeneralMixinFields0 := profitgeneralMixin[0].Fields()
	_ = profitgeneralMixinFields0
	profitgeneralFields := schema.ProfitGeneral{}.Fields()
	_ = profitgeneralFields
	// profitgeneralDescCreatedAt is the schema descriptor for created_at field.
	profitgeneralDescCreatedAt := profitgeneralMixinFields0[0].Descriptor()
	// profitgeneral.DefaultCreatedAt holds the default value on creation for the created_at field.
	profitgeneral.DefaultCreatedAt = profitgeneralDescCreatedAt.Default.(func() uint32)
	// profitgeneralDescUpdatedAt is the schema descriptor for updated_at field.
	profitgeneralDescUpdatedAt := profitgeneralMixinFields0[1].Descriptor()
	// profitgeneral.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profitgeneral.DefaultUpdatedAt = profitgeneralDescUpdatedAt.Default.(func() uint32)
	// profitgeneral.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profitgeneral.UpdateDefaultUpdatedAt = profitgeneralDescUpdatedAt.UpdateDefault.(func() uint32)
	// profitgeneralDescDeletedAt is the schema descriptor for deleted_at field.
	profitgeneralDescDeletedAt := profitgeneralMixinFields0[2].Descriptor()
	// profitgeneral.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	profitgeneral.DefaultDeletedAt = profitgeneralDescDeletedAt.Default.(func() uint32)
	// profitgeneralDescGoodID is the schema descriptor for good_id field.
	profitgeneralDescGoodID := profitgeneralFields[1].Descriptor()
	// profitgeneral.DefaultGoodID holds the default value on creation for the good_id field.
	profitgeneral.DefaultGoodID = profitgeneralDescGoodID.Default.(func() uuid.UUID)
	// profitgeneralDescCoinTypeID is the schema descriptor for coin_type_id field.
	profitgeneralDescCoinTypeID := profitgeneralFields[2].Descriptor()
	// profitgeneral.DefaultCoinTypeID holds the default value on creation for the coin_type_id field.
	profitgeneral.DefaultCoinTypeID = profitgeneralDescCoinTypeID.Default.(func() uuid.UUID)
	// profitgeneralDescID is the schema descriptor for id field.
	profitgeneralDescID := profitgeneralFields[0].Descriptor()
	// profitgeneral.DefaultID holds the default value on creation for the id field.
	profitgeneral.DefaultID = profitgeneralDescID.Default.(func() uuid.UUID)
	profitunsoldMixin := schema.ProfitUnsold{}.Mixin()
	profitunsold.Policy = privacy.NewPolicies(profitunsoldMixin[0], schema.ProfitUnsold{})
	profitunsold.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := profitunsold.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	profitunsoldMixinFields0 := profitunsoldMixin[0].Fields()
	_ = profitunsoldMixinFields0
	profitunsoldFields := schema.ProfitUnsold{}.Fields()
	_ = profitunsoldFields
	// profitunsoldDescCreatedAt is the schema descriptor for created_at field.
	profitunsoldDescCreatedAt := profitunsoldMixinFields0[0].Descriptor()
	// profitunsold.DefaultCreatedAt holds the default value on creation for the created_at field.
	profitunsold.DefaultCreatedAt = profitunsoldDescCreatedAt.Default.(func() uint32)
	// profitunsoldDescUpdatedAt is the schema descriptor for updated_at field.
	profitunsoldDescUpdatedAt := profitunsoldMixinFields0[1].Descriptor()
	// profitunsold.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	profitunsold.DefaultUpdatedAt = profitunsoldDescUpdatedAt.Default.(func() uint32)
	// profitunsold.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	profitunsold.UpdateDefaultUpdatedAt = profitunsoldDescUpdatedAt.UpdateDefault.(func() uint32)
	// profitunsoldDescDeletedAt is the schema descriptor for deleted_at field.
	profitunsoldDescDeletedAt := profitunsoldMixinFields0[2].Descriptor()
	// profitunsold.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	profitunsold.DefaultDeletedAt = profitunsoldDescDeletedAt.Default.(func() uint32)
	// profitunsoldDescGoodID is the schema descriptor for good_id field.
	profitunsoldDescGoodID := profitunsoldFields[1].Descriptor()
	// profitunsold.DefaultGoodID holds the default value on creation for the good_id field.
	profitunsold.DefaultGoodID = profitunsoldDescGoodID.Default.(func() uuid.UUID)
	// profitunsoldDescCoinTypeID is the schema descriptor for coin_type_id field.
	profitunsoldDescCoinTypeID := profitunsoldFields[2].Descriptor()
	// profitunsold.DefaultCoinTypeID holds the default value on creation for the coin_type_id field.
	profitunsold.DefaultCoinTypeID = profitunsoldDescCoinTypeID.Default.(func() uuid.UUID)
	// profitunsoldDescBenefitDate is the schema descriptor for benefit_date field.
	profitunsoldDescBenefitDate := profitunsoldFields[4].Descriptor()
	// profitunsold.DefaultBenefitDate holds the default value on creation for the benefit_date field.
	profitunsold.DefaultBenefitDate = profitunsoldDescBenefitDate.Default.(uint32)
	// profitunsoldDescID is the schema descriptor for id field.
	profitunsoldDescID := profitunsoldFields[0].Descriptor()
	// profitunsold.DefaultID holds the default value on creation for the id field.
	profitunsold.DefaultID = profitunsoldDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.10.1"                                         // Version of ent codegen.
	Sum     = "h1:dM5h4Zk6yHGIgw4dCqVzGw3nWgpGYJiV4/kyHEF6PFo=" // Sum of ent codegen.
)
