// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitgeneral"
)

// ProfitGeneralDelete is the builder for deleting a ProfitGeneral entity.
type ProfitGeneralDelete struct {
	config
	hooks    []Hook
	mutation *ProfitGeneralMutation
}

// Where appends a list predicates to the ProfitGeneralDelete builder.
func (pgd *ProfitGeneralDelete) Where(ps ...predicate.ProfitGeneral) *ProfitGeneralDelete {
	pgd.mutation.Where(ps...)
	return pgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pgd *ProfitGeneralDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pgd.hooks) == 0 {
		affected, err = pgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProfitGeneralMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pgd.mutation = mutation
			affected, err = pgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pgd.hooks) - 1; i >= 0; i-- {
			if pgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgd *ProfitGeneralDelete) ExecX(ctx context.Context) int {
	n, err := pgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pgd *ProfitGeneralDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: profitgeneral.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: profitgeneral.FieldID,
			},
		},
	}
	if ps := pgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pgd.driver, _spec)
}

// ProfitGeneralDeleteOne is the builder for deleting a single ProfitGeneral entity.
type ProfitGeneralDeleteOne struct {
	pgd *ProfitGeneralDelete
}

// Exec executes the deletion query.
func (pgdo *ProfitGeneralDeleteOne) Exec(ctx context.Context) error {
	n, err := pgdo.pgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{profitgeneral.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pgdo *ProfitGeneralDeleteOne) ExecX(ctx context.Context) {
	pgdo.pgd.ExecX(ctx)
}
