// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitgeneral"
	"github.com/google/uuid"
)

// ProfitGeneralQuery is the builder for querying ProfitGeneral entities.
type ProfitGeneralQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProfitGeneral
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfitGeneralQuery builder.
func (pgq *ProfitGeneralQuery) Where(ps ...predicate.ProfitGeneral) *ProfitGeneralQuery {
	pgq.predicates = append(pgq.predicates, ps...)
	return pgq
}

// Limit adds a limit step to the query.
func (pgq *ProfitGeneralQuery) Limit(limit int) *ProfitGeneralQuery {
	pgq.limit = &limit
	return pgq
}

// Offset adds an offset step to the query.
func (pgq *ProfitGeneralQuery) Offset(offset int) *ProfitGeneralQuery {
	pgq.offset = &offset
	return pgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pgq *ProfitGeneralQuery) Unique(unique bool) *ProfitGeneralQuery {
	pgq.unique = &unique
	return pgq
}

// Order adds an order step to the query.
func (pgq *ProfitGeneralQuery) Order(o ...OrderFunc) *ProfitGeneralQuery {
	pgq.order = append(pgq.order, o...)
	return pgq
}

// First returns the first ProfitGeneral entity from the query.
// Returns a *NotFoundError when no ProfitGeneral was found.
func (pgq *ProfitGeneralQuery) First(ctx context.Context) (*ProfitGeneral, error) {
	nodes, err := pgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profitgeneral.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) FirstX(ctx context.Context) *ProfitGeneral {
	node, err := pgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfitGeneral ID from the query.
// Returns a *NotFoundError when no ProfitGeneral ID was found.
func (pgq *ProfitGeneralQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profitgeneral.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfitGeneral entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfitGeneral entity is found.
// Returns a *NotFoundError when no ProfitGeneral entities are found.
func (pgq *ProfitGeneralQuery) Only(ctx context.Context) (*ProfitGeneral, error) {
	nodes, err := pgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profitgeneral.Label}
	default:
		return nil, &NotSingularError{profitgeneral.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) OnlyX(ctx context.Context) *ProfitGeneral {
	node, err := pgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfitGeneral ID in the query.
// Returns a *NotSingularError when more than one ProfitGeneral ID is found.
// Returns a *NotFoundError when no entities are found.
func (pgq *ProfitGeneralQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = &NotSingularError{profitgeneral.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfitGenerals.
func (pgq *ProfitGeneralQuery) All(ctx context.Context) ([]*ProfitGeneral, error) {
	if err := pgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) AllX(ctx context.Context) []*ProfitGeneral {
	nodes, err := pgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfitGeneral IDs.
func (pgq *ProfitGeneralQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := pgq.Select(profitgeneral.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pgq *ProfitGeneralQuery) Count(ctx context.Context) (int, error) {
	if err := pgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) CountX(ctx context.Context) int {
	count, err := pgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pgq *ProfitGeneralQuery) Exist(ctx context.Context) (bool, error) {
	if err := pgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pgq *ProfitGeneralQuery) ExistX(ctx context.Context) bool {
	exist, err := pgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfitGeneralQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pgq *ProfitGeneralQuery) Clone() *ProfitGeneralQuery {
	if pgq == nil {
		return nil
	}
	return &ProfitGeneralQuery{
		config:     pgq.config,
		limit:      pgq.limit,
		offset:     pgq.offset,
		order:      append([]OrderFunc{}, pgq.order...),
		predicates: append([]predicate.ProfitGeneral{}, pgq.predicates...),
		// clone intermediate query.
		sql:    pgq.sql.Clone(),
		path:   pgq.path,
		unique: pgq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfitGeneral.Query().
//		GroupBy(profitgeneral.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pgq *ProfitGeneralQuery) GroupBy(field string, fields ...string) *ProfitGeneralGroupBy {
	group := &ProfitGeneralGroupBy{config: pgq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pgq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.ProfitGeneral.Query().
//		Select(profitgeneral.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (pgq *ProfitGeneralQuery) Select(fields ...string) *ProfitGeneralSelect {
	pgq.fields = append(pgq.fields, fields...)
	return &ProfitGeneralSelect{ProfitGeneralQuery: pgq}
}

func (pgq *ProfitGeneralQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pgq.fields {
		if !profitgeneral.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pgq.path != nil {
		prev, err := pgq.path(ctx)
		if err != nil {
			return err
		}
		pgq.sql = prev
	}
	if profitgeneral.Policy == nil {
		return errors.New("ent: uninitialized profitgeneral.Policy (forgotten import ent/runtime?)")
	}
	if err := profitgeneral.Policy.EvalQuery(ctx, pgq); err != nil {
		return err
	}
	return nil
}

func (pgq *ProfitGeneralQuery) sqlAll(ctx context.Context) ([]*ProfitGeneral, error) {
	var (
		nodes = []*ProfitGeneral{}
		_spec = pgq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProfitGeneral{config: pgq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(pgq.modifiers) > 0 {
		_spec.Modifiers = pgq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, pgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pgq *ProfitGeneralQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pgq.querySpec()
	if len(pgq.modifiers) > 0 {
		_spec.Modifiers = pgq.modifiers
	}
	_spec.Node.Columns = pgq.fields
	if len(pgq.fields) > 0 {
		_spec.Unique = pgq.unique != nil && *pgq.unique
	}
	return sqlgraph.CountNodes(ctx, pgq.driver, _spec)
}

func (pgq *ProfitGeneralQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pgq *ProfitGeneralQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profitgeneral.Table,
			Columns: profitgeneral.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: profitgeneral.FieldID,
			},
		},
		From:   pgq.sql,
		Unique: true,
	}
	if unique := pgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profitgeneral.FieldID)
		for i := range fields {
			if fields[i] != profitgeneral.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pgq *ProfitGeneralQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pgq.driver.Dialect())
	t1 := builder.Table(profitgeneral.Table)
	columns := pgq.fields
	if len(columns) == 0 {
		columns = profitgeneral.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pgq.sql != nil {
		selector = pgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pgq.unique != nil && *pgq.unique {
		selector.Distinct()
	}
	for _, m := range pgq.modifiers {
		m(selector)
	}
	for _, p := range pgq.predicates {
		p(selector)
	}
	for _, p := range pgq.order {
		p(selector)
	}
	if offset := pgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (pgq *ProfitGeneralQuery) ForUpdate(opts ...sql.LockOption) *ProfitGeneralQuery {
	if pgq.driver.Dialect() == dialect.Postgres {
		pgq.Unique(false)
	}
	pgq.modifiers = append(pgq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return pgq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (pgq *ProfitGeneralQuery) ForShare(opts ...sql.LockOption) *ProfitGeneralQuery {
	if pgq.driver.Dialect() == dialect.Postgres {
		pgq.Unique(false)
	}
	pgq.modifiers = append(pgq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return pgq
}

// ProfitGeneralGroupBy is the group-by builder for ProfitGeneral entities.
type ProfitGeneralGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pggb *ProfitGeneralGroupBy) Aggregate(fns ...AggregateFunc) *ProfitGeneralGroupBy {
	pggb.fns = append(pggb.fns, fns...)
	return pggb
}

// Scan applies the group-by query and scans the result into the given value.
func (pggb *ProfitGeneralGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pggb.path(ctx)
	if err != nil {
		return err
	}
	pggb.sql = query
	return pggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) StringsX(ctx context.Context) []string {
	v, err := pggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) StringX(ctx context.Context) string {
	v, err := pggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) IntsX(ctx context.Context) []int {
	v, err := pggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) IntX(ctx context.Context) int {
	v, err := pggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pggb.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pggb *ProfitGeneralGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pggb *ProfitGeneralGroupBy) BoolX(ctx context.Context) bool {
	v, err := pggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pggb *ProfitGeneralGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pggb.fields {
		if !profitgeneral.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pggb *ProfitGeneralGroupBy) sqlQuery() *sql.Selector {
	selector := pggb.sql.Select()
	aggregation := make([]string, 0, len(pggb.fns))
	for _, fn := range pggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pggb.fields)+len(pggb.fns))
		for _, f := range pggb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pggb.fields...)...)
}

// ProfitGeneralSelect is the builder for selecting fields of ProfitGeneral entities.
type ProfitGeneralSelect struct {
	*ProfitGeneralQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pgs *ProfitGeneralSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pgs.prepareQuery(ctx); err != nil {
		return err
	}
	pgs.sql = pgs.ProfitGeneralQuery.sqlQuery(ctx)
	return pgs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pgs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) StringsX(ctx context.Context) []string {
	v, err := pgs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pgs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) StringX(ctx context.Context) string {
	v, err := pgs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) IntsX(ctx context.Context) []int {
	v, err := pgs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pgs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) IntX(ctx context.Context) int {
	v, err := pgs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pgs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pgs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) Float64X(ctx context.Context) float64 {
	v, err := pgs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pgs.fields) > 1 {
		return nil, errors.New("ent: ProfitGeneralSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) BoolsX(ctx context.Context) []bool {
	v, err := pgs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pgs *ProfitGeneralSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pgs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitgeneral.Label}
	default:
		err = fmt.Errorf("ent: ProfitGeneralSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pgs *ProfitGeneralSelect) BoolX(ctx context.Context) bool {
	v, err := pgs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pgs *ProfitGeneralSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pgs.sql.Query()
	if err := pgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
