// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitdetail"
	"github.com/google/uuid"
)

// ProfitDetailQuery is the builder for querying ProfitDetail entities.
type ProfitDetailQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProfitDetail
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfitDetailQuery builder.
func (pdq *ProfitDetailQuery) Where(ps ...predicate.ProfitDetail) *ProfitDetailQuery {
	pdq.predicates = append(pdq.predicates, ps...)
	return pdq
}

// Limit adds a limit step to the query.
func (pdq *ProfitDetailQuery) Limit(limit int) *ProfitDetailQuery {
	pdq.limit = &limit
	return pdq
}

// Offset adds an offset step to the query.
func (pdq *ProfitDetailQuery) Offset(offset int) *ProfitDetailQuery {
	pdq.offset = &offset
	return pdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pdq *ProfitDetailQuery) Unique(unique bool) *ProfitDetailQuery {
	pdq.unique = &unique
	return pdq
}

// Order adds an order step to the query.
func (pdq *ProfitDetailQuery) Order(o ...OrderFunc) *ProfitDetailQuery {
	pdq.order = append(pdq.order, o...)
	return pdq
}

// First returns the first ProfitDetail entity from the query.
// Returns a *NotFoundError when no ProfitDetail was found.
func (pdq *ProfitDetailQuery) First(ctx context.Context) (*ProfitDetail, error) {
	nodes, err := pdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profitdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pdq *ProfitDetailQuery) FirstX(ctx context.Context) *ProfitDetail {
	node, err := pdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfitDetail ID from the query.
// Returns a *NotFoundError when no ProfitDetail ID was found.
func (pdq *ProfitDetailQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profitdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pdq *ProfitDetailQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfitDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfitDetail entity is found.
// Returns a *NotFoundError when no ProfitDetail entities are found.
func (pdq *ProfitDetailQuery) Only(ctx context.Context) (*ProfitDetail, error) {
	nodes, err := pdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profitdetail.Label}
	default:
		return nil, &NotSingularError{profitdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pdq *ProfitDetailQuery) OnlyX(ctx context.Context) *ProfitDetail {
	node, err := pdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfitDetail ID in the query.
// Returns a *NotSingularError when more than one ProfitDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (pdq *ProfitDetailQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = &NotSingularError{profitdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pdq *ProfitDetailQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfitDetails.
func (pdq *ProfitDetailQuery) All(ctx context.Context) ([]*ProfitDetail, error) {
	if err := pdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pdq *ProfitDetailQuery) AllX(ctx context.Context) []*ProfitDetail {
	nodes, err := pdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfitDetail IDs.
func (pdq *ProfitDetailQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := pdq.Select(profitdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pdq *ProfitDetailQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pdq *ProfitDetailQuery) Count(ctx context.Context) (int, error) {
	if err := pdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pdq *ProfitDetailQuery) CountX(ctx context.Context) int {
	count, err := pdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pdq *ProfitDetailQuery) Exist(ctx context.Context) (bool, error) {
	if err := pdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pdq *ProfitDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := pdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfitDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pdq *ProfitDetailQuery) Clone() *ProfitDetailQuery {
	if pdq == nil {
		return nil
	}
	return &ProfitDetailQuery{
		config:     pdq.config,
		limit:      pdq.limit,
		offset:     pdq.offset,
		order:      append([]OrderFunc{}, pdq.order...),
		predicates: append([]predicate.ProfitDetail{}, pdq.predicates...),
		// clone intermediate query.
		sql:    pdq.sql.Clone(),
		path:   pdq.path,
		unique: pdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfitDetail.Query().
//		GroupBy(profitdetail.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pdq *ProfitDetailQuery) GroupBy(field string, fields ...string) *ProfitDetailGroupBy {
	group := &ProfitDetailGroupBy{config: pdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.ProfitDetail.Query().
//		Select(profitdetail.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (pdq *ProfitDetailQuery) Select(fields ...string) *ProfitDetailSelect {
	pdq.fields = append(pdq.fields, fields...)
	return &ProfitDetailSelect{ProfitDetailQuery: pdq}
}

func (pdq *ProfitDetailQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pdq.fields {
		if !profitdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pdq.path != nil {
		prev, err := pdq.path(ctx)
		if err != nil {
			return err
		}
		pdq.sql = prev
	}
	if profitdetail.Policy == nil {
		return errors.New("ent: uninitialized profitdetail.Policy (forgotten import ent/runtime?)")
	}
	if err := profitdetail.Policy.EvalQuery(ctx, pdq); err != nil {
		return err
	}
	return nil
}

func (pdq *ProfitDetailQuery) sqlAll(ctx context.Context) ([]*ProfitDetail, error) {
	var (
		nodes = []*ProfitDetail{}
		_spec = pdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProfitDetail{config: pdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(pdq.modifiers) > 0 {
		_spec.Modifiers = pdq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, pdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pdq *ProfitDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pdq.querySpec()
	if len(pdq.modifiers) > 0 {
		_spec.Modifiers = pdq.modifiers
	}
	_spec.Node.Columns = pdq.fields
	if len(pdq.fields) > 0 {
		_spec.Unique = pdq.unique != nil && *pdq.unique
	}
	return sqlgraph.CountNodes(ctx, pdq.driver, _spec)
}

func (pdq *ProfitDetailQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pdq *ProfitDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profitdetail.Table,
			Columns: profitdetail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: profitdetail.FieldID,
			},
		},
		From:   pdq.sql,
		Unique: true,
	}
	if unique := pdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profitdetail.FieldID)
		for i := range fields {
			if fields[i] != profitdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pdq *ProfitDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pdq.driver.Dialect())
	t1 := builder.Table(profitdetail.Table)
	columns := pdq.fields
	if len(columns) == 0 {
		columns = profitdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pdq.sql != nil {
		selector = pdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pdq.unique != nil && *pdq.unique {
		selector.Distinct()
	}
	for _, m := range pdq.modifiers {
		m(selector)
	}
	for _, p := range pdq.predicates {
		p(selector)
	}
	for _, p := range pdq.order {
		p(selector)
	}
	if offset := pdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (pdq *ProfitDetailQuery) ForUpdate(opts ...sql.LockOption) *ProfitDetailQuery {
	if pdq.driver.Dialect() == dialect.Postgres {
		pdq.Unique(false)
	}
	pdq.modifiers = append(pdq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return pdq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (pdq *ProfitDetailQuery) ForShare(opts ...sql.LockOption) *ProfitDetailQuery {
	if pdq.driver.Dialect() == dialect.Postgres {
		pdq.Unique(false)
	}
	pdq.modifiers = append(pdq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return pdq
}

// ProfitDetailGroupBy is the group-by builder for ProfitDetail entities.
type ProfitDetailGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pdgb *ProfitDetailGroupBy) Aggregate(fns ...AggregateFunc) *ProfitDetailGroupBy {
	pdgb.fns = append(pdgb.fns, fns...)
	return pdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pdgb *ProfitDetailGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pdgb.path(ctx)
	if err != nil {
		return err
	}
	pdgb.sql = query
	return pdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pdgb.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) StringsX(ctx context.Context) []string {
	v, err := pdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) StringX(ctx context.Context) string {
	v, err := pdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pdgb.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) IntsX(ctx context.Context) []int {
	v, err := pdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) IntX(ctx context.Context) int {
	v, err := pdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pdgb.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pdgb.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pdgb *ProfitDetailGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pdgb *ProfitDetailGroupBy) BoolX(ctx context.Context) bool {
	v, err := pdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pdgb *ProfitDetailGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pdgb.fields {
		if !profitdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pdgb *ProfitDetailGroupBy) sqlQuery() *sql.Selector {
	selector := pdgb.sql.Select()
	aggregation := make([]string, 0, len(pdgb.fns))
	for _, fn := range pdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pdgb.fields)+len(pdgb.fns))
		for _, f := range pdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pdgb.fields...)...)
}

// ProfitDetailSelect is the builder for selecting fields of ProfitDetail entities.
type ProfitDetailSelect struct {
	*ProfitDetailQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pds *ProfitDetailSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pds.prepareQuery(ctx); err != nil {
		return err
	}
	pds.sql = pds.ProfitDetailQuery.sqlQuery(ctx)
	return pds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pds *ProfitDetailSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pds.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pds *ProfitDetailSelect) StringsX(ctx context.Context) []string {
	v, err := pds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pds *ProfitDetailSelect) StringX(ctx context.Context) string {
	v, err := pds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pds.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pds *ProfitDetailSelect) IntsX(ctx context.Context) []int {
	v, err := pds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pds *ProfitDetailSelect) IntX(ctx context.Context) int {
	v, err := pds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pds.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pds *ProfitDetailSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pds *ProfitDetailSelect) Float64X(ctx context.Context) float64 {
	v, err := pds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pds.fields) > 1 {
		return nil, errors.New("ent: ProfitDetailSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pds *ProfitDetailSelect) BoolsX(ctx context.Context) []bool {
	v, err := pds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pds *ProfitDetailSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitdetail.Label}
	default:
		err = fmt.Errorf("ent: ProfitDetailSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pds *ProfitDetailSelect) BoolX(ctx context.Context) bool {
	v, err := pds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pds *ProfitDetailSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pds.sql.Query()
	if err := pds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
