// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitgeneral"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ProfitGeneral is the model entity for the ProfitGeneral schema.
type ProfitGeneral struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// GoodID holds the value of the "good_id" field.
	GoodID uuid.UUID `json:"good_id,omitempty"`
	// CoinTypeID holds the value of the "coin_type_id" field.
	CoinTypeID uuid.UUID `json:"coin_type_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// ToPlatform holds the value of the "to_platform" field.
	ToPlatform decimal.Decimal `json:"to_platform,omitempty"`
	// ToUser holds the value of the "to_user" field.
	ToUser decimal.Decimal `json:"to_user,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProfitGeneral) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case profitgeneral.FieldAmount, profitgeneral.FieldToPlatform, profitgeneral.FieldToUser:
			values[i] = new(decimal.Decimal)
		case profitgeneral.FieldCreatedAt, profitgeneral.FieldUpdatedAt, profitgeneral.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case profitgeneral.FieldID, profitgeneral.FieldGoodID, profitgeneral.FieldCoinTypeID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ProfitGeneral", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProfitGeneral fields.
func (pg *ProfitGeneral) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profitgeneral.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pg.ID = *value
			}
		case profitgeneral.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pg.CreatedAt = uint32(value.Int64)
			}
		case profitgeneral.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pg.UpdatedAt = uint32(value.Int64)
			}
		case profitgeneral.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				pg.DeletedAt = uint32(value.Int64)
			}
		case profitgeneral.FieldGoodID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field good_id", values[i])
			} else if value != nil {
				pg.GoodID = *value
			}
		case profitgeneral.FieldCoinTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_type_id", values[i])
			} else if value != nil {
				pg.CoinTypeID = *value
			}
		case profitgeneral.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				pg.Amount = *value
			}
		case profitgeneral.FieldToPlatform:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field to_platform", values[i])
			} else if value != nil {
				pg.ToPlatform = *value
			}
		case profitgeneral.FieldToUser:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field to_user", values[i])
			} else if value != nil {
				pg.ToUser = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this ProfitGeneral.
// Note that you need to call ProfitGeneral.Unwrap() before calling this method if this ProfitGeneral
// was returned from a transaction, and the transaction was committed or rolled back.
func (pg *ProfitGeneral) Update() *ProfitGeneralUpdateOne {
	return (&ProfitGeneralClient{config: pg.config}).UpdateOne(pg)
}

// Unwrap unwraps the ProfitGeneral entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pg *ProfitGeneral) Unwrap() *ProfitGeneral {
	tx, ok := pg.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProfitGeneral is not a transactional entity")
	}
	pg.config.driver = tx.drv
	return pg
}

// String implements the fmt.Stringer.
func (pg *ProfitGeneral) String() string {
	var builder strings.Builder
	builder.WriteString("ProfitGeneral(")
	builder.WriteString(fmt.Sprintf("id=%v", pg.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(fmt.Sprintf("%v", pg.CreatedAt))
	builder.WriteString(", updated_at=")
	builder.WriteString(fmt.Sprintf("%v", pg.UpdatedAt))
	builder.WriteString(", deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", pg.DeletedAt))
	builder.WriteString(", good_id=")
	builder.WriteString(fmt.Sprintf("%v", pg.GoodID))
	builder.WriteString(", coin_type_id=")
	builder.WriteString(fmt.Sprintf("%v", pg.CoinTypeID))
	builder.WriteString(", amount=")
	builder.WriteString(fmt.Sprintf("%v", pg.Amount))
	builder.WriteString(", to_platform=")
	builder.WriteString(fmt.Sprintf("%v", pg.ToPlatform))
	builder.WriteString(", to_user=")
	builder.WriteString(fmt.Sprintf("%v", pg.ToUser))
	builder.WriteByte(')')
	return builder.String()
}

// ProfitGenerals is a parsable slice of ProfitGeneral.
type ProfitGenerals []*ProfitGeneral

func (pg ProfitGenerals) config(cfg config) {
	for _i := range pg {
		pg[_i].config = cfg
	}
}
