// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitunsold"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ProfitUnsold is the model entity for the ProfitUnsold schema.
type ProfitUnsold struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// GoodID holds the value of the "good_id" field.
	GoodID uuid.UUID `json:"good_id,omitempty"`
	// CoinTypeID holds the value of the "coin_type_id" field.
	CoinTypeID uuid.UUID `json:"coin_type_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// BenefitDate holds the value of the "benefit_date" field.
	BenefitDate uint32 `json:"benefit_date,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProfitUnsold) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case profitunsold.FieldAmount:
			values[i] = new(decimal.Decimal)
		case profitunsold.FieldCreatedAt, profitunsold.FieldUpdatedAt, profitunsold.FieldDeletedAt, profitunsold.FieldBenefitDate:
			values[i] = new(sql.NullInt64)
		case profitunsold.FieldID, profitunsold.FieldGoodID, profitunsold.FieldCoinTypeID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ProfitUnsold", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProfitUnsold fields.
func (pu *ProfitUnsold) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case profitunsold.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pu.ID = *value
			}
		case profitunsold.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pu.CreatedAt = uint32(value.Int64)
			}
		case profitunsold.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pu.UpdatedAt = uint32(value.Int64)
			}
		case profitunsold.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				pu.DeletedAt = uint32(value.Int64)
			}
		case profitunsold.FieldGoodID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field good_id", values[i])
			} else if value != nil {
				pu.GoodID = *value
			}
		case profitunsold.FieldCoinTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_type_id", values[i])
			} else if value != nil {
				pu.CoinTypeID = *value
			}
		case profitunsold.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				pu.Amount = *value
			}
		case profitunsold.FieldBenefitDate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field benefit_date", values[i])
			} else if value.Valid {
				pu.BenefitDate = uint32(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this ProfitUnsold.
// Note that you need to call ProfitUnsold.Unwrap() before calling this method if this ProfitUnsold
// was returned from a transaction, and the transaction was committed or rolled back.
func (pu *ProfitUnsold) Update() *ProfitUnsoldUpdateOne {
	return (&ProfitUnsoldClient{config: pu.config}).UpdateOne(pu)
}

// Unwrap unwraps the ProfitUnsold entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pu *ProfitUnsold) Unwrap() *ProfitUnsold {
	tx, ok := pu.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProfitUnsold is not a transactional entity")
	}
	pu.config.driver = tx.drv
	return pu
}

// String implements the fmt.Stringer.
func (pu *ProfitUnsold) String() string {
	var builder strings.Builder
	builder.WriteString("ProfitUnsold(")
	builder.WriteString(fmt.Sprintf("id=%v", pu.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(fmt.Sprintf("%v", pu.CreatedAt))
	builder.WriteString(", updated_at=")
	builder.WriteString(fmt.Sprintf("%v", pu.UpdatedAt))
	builder.WriteString(", deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", pu.DeletedAt))
	builder.WriteString(", good_id=")
	builder.WriteString(fmt.Sprintf("%v", pu.GoodID))
	builder.WriteString(", coin_type_id=")
	builder.WriteString(fmt.Sprintf("%v", pu.CoinTypeID))
	builder.WriteString(", amount=")
	builder.WriteString(fmt.Sprintf("%v", pu.Amount))
	builder.WriteString(", benefit_date=")
	builder.WriteString(fmt.Sprintf("%v", pu.BenefitDate))
	builder.WriteByte(')')
	return builder.String()
}

// ProfitUnsolds is a parsable slice of ProfitUnsold.
type ProfitUnsolds []*ProfitUnsold

func (pu ProfitUnsolds) config(cfg config) {
	for _i := range pu {
		pu[_i].config = cfg
	}
}
