// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/mining-manager/pkg/db/ent/profitunsold"
	"github.com/google/uuid"
)

// ProfitUnsoldQuery is the builder for querying ProfitUnsold entities.
type ProfitUnsoldQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProfitUnsold
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfitUnsoldQuery builder.
func (puq *ProfitUnsoldQuery) Where(ps ...predicate.ProfitUnsold) *ProfitUnsoldQuery {
	puq.predicates = append(puq.predicates, ps...)
	return puq
}

// Limit adds a limit step to the query.
func (puq *ProfitUnsoldQuery) Limit(limit int) *ProfitUnsoldQuery {
	puq.limit = &limit
	return puq
}

// Offset adds an offset step to the query.
func (puq *ProfitUnsoldQuery) Offset(offset int) *ProfitUnsoldQuery {
	puq.offset = &offset
	return puq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (puq *ProfitUnsoldQuery) Unique(unique bool) *ProfitUnsoldQuery {
	puq.unique = &unique
	return puq
}

// Order adds an order step to the query.
func (puq *ProfitUnsoldQuery) Order(o ...OrderFunc) *ProfitUnsoldQuery {
	puq.order = append(puq.order, o...)
	return puq
}

// First returns the first ProfitUnsold entity from the query.
// Returns a *NotFoundError when no ProfitUnsold was found.
func (puq *ProfitUnsoldQuery) First(ctx context.Context) (*ProfitUnsold, error) {
	nodes, err := puq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profitunsold.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) FirstX(ctx context.Context) *ProfitUnsold {
	node, err := puq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfitUnsold ID from the query.
// Returns a *NotFoundError when no ProfitUnsold ID was found.
func (puq *ProfitUnsoldQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = puq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profitunsold.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := puq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfitUnsold entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfitUnsold entity is found.
// Returns a *NotFoundError when no ProfitUnsold entities are found.
func (puq *ProfitUnsoldQuery) Only(ctx context.Context) (*ProfitUnsold, error) {
	nodes, err := puq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profitunsold.Label}
	default:
		return nil, &NotSingularError{profitunsold.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) OnlyX(ctx context.Context) *ProfitUnsold {
	node, err := puq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfitUnsold ID in the query.
// Returns a *NotSingularError when more than one ProfitUnsold ID is found.
// Returns a *NotFoundError when no entities are found.
func (puq *ProfitUnsoldQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = puq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = &NotSingularError{profitunsold.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := puq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfitUnsolds.
func (puq *ProfitUnsoldQuery) All(ctx context.Context) ([]*ProfitUnsold, error) {
	if err := puq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return puq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) AllX(ctx context.Context) []*ProfitUnsold {
	nodes, err := puq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfitUnsold IDs.
func (puq *ProfitUnsoldQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := puq.Select(profitunsold.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := puq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (puq *ProfitUnsoldQuery) Count(ctx context.Context) (int, error) {
	if err := puq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return puq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) CountX(ctx context.Context) int {
	count, err := puq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (puq *ProfitUnsoldQuery) Exist(ctx context.Context) (bool, error) {
	if err := puq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return puq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (puq *ProfitUnsoldQuery) ExistX(ctx context.Context) bool {
	exist, err := puq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfitUnsoldQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (puq *ProfitUnsoldQuery) Clone() *ProfitUnsoldQuery {
	if puq == nil {
		return nil
	}
	return &ProfitUnsoldQuery{
		config:     puq.config,
		limit:      puq.limit,
		offset:     puq.offset,
		order:      append([]OrderFunc{}, puq.order...),
		predicates: append([]predicate.ProfitUnsold{}, puq.predicates...),
		// clone intermediate query.
		sql:    puq.sql.Clone(),
		path:   puq.path,
		unique: puq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProfitUnsold.Query().
//		GroupBy(profitunsold.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (puq *ProfitUnsoldQuery) GroupBy(field string, fields ...string) *ProfitUnsoldGroupBy {
	group := &ProfitUnsoldGroupBy{config: puq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := puq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return puq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.ProfitUnsold.Query().
//		Select(profitunsold.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (puq *ProfitUnsoldQuery) Select(fields ...string) *ProfitUnsoldSelect {
	puq.fields = append(puq.fields, fields...)
	return &ProfitUnsoldSelect{ProfitUnsoldQuery: puq}
}

func (puq *ProfitUnsoldQuery) prepareQuery(ctx context.Context) error {
	for _, f := range puq.fields {
		if !profitunsold.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if puq.path != nil {
		prev, err := puq.path(ctx)
		if err != nil {
			return err
		}
		puq.sql = prev
	}
	if profitunsold.Policy == nil {
		return errors.New("ent: uninitialized profitunsold.Policy (forgotten import ent/runtime?)")
	}
	if err := profitunsold.Policy.EvalQuery(ctx, puq); err != nil {
		return err
	}
	return nil
}

func (puq *ProfitUnsoldQuery) sqlAll(ctx context.Context) ([]*ProfitUnsold, error) {
	var (
		nodes = []*ProfitUnsold{}
		_spec = puq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProfitUnsold{config: puq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(puq.modifiers) > 0 {
		_spec.Modifiers = puq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, puq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (puq *ProfitUnsoldQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := puq.querySpec()
	if len(puq.modifiers) > 0 {
		_spec.Modifiers = puq.modifiers
	}
	_spec.Node.Columns = puq.fields
	if len(puq.fields) > 0 {
		_spec.Unique = puq.unique != nil && *puq.unique
	}
	return sqlgraph.CountNodes(ctx, puq.driver, _spec)
}

func (puq *ProfitUnsoldQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := puq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (puq *ProfitUnsoldQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   profitunsold.Table,
			Columns: profitunsold.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: profitunsold.FieldID,
			},
		},
		From:   puq.sql,
		Unique: true,
	}
	if unique := puq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := puq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profitunsold.FieldID)
		for i := range fields {
			if fields[i] != profitunsold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := puq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := puq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := puq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := puq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (puq *ProfitUnsoldQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(puq.driver.Dialect())
	t1 := builder.Table(profitunsold.Table)
	columns := puq.fields
	if len(columns) == 0 {
		columns = profitunsold.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if puq.sql != nil {
		selector = puq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if puq.unique != nil && *puq.unique {
		selector.Distinct()
	}
	for _, m := range puq.modifiers {
		m(selector)
	}
	for _, p := range puq.predicates {
		p(selector)
	}
	for _, p := range puq.order {
		p(selector)
	}
	if offset := puq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := puq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (puq *ProfitUnsoldQuery) ForUpdate(opts ...sql.LockOption) *ProfitUnsoldQuery {
	if puq.driver.Dialect() == dialect.Postgres {
		puq.Unique(false)
	}
	puq.modifiers = append(puq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return puq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (puq *ProfitUnsoldQuery) ForShare(opts ...sql.LockOption) *ProfitUnsoldQuery {
	if puq.driver.Dialect() == dialect.Postgres {
		puq.Unique(false)
	}
	puq.modifiers = append(puq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return puq
}

// ProfitUnsoldGroupBy is the group-by builder for ProfitUnsold entities.
type ProfitUnsoldGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pugb *ProfitUnsoldGroupBy) Aggregate(fns ...AggregateFunc) *ProfitUnsoldGroupBy {
	pugb.fns = append(pugb.fns, fns...)
	return pugb
}

// Scan applies the group-by query and scans the result into the given value.
func (pugb *ProfitUnsoldGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pugb.path(ctx)
	if err != nil {
		return err
	}
	pugb.sql = query
	return pugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pugb.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) StringsX(ctx context.Context) []string {
	v, err := pugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) StringX(ctx context.Context) string {
	v, err := pugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pugb.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) IntsX(ctx context.Context) []int {
	v, err := pugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) IntX(ctx context.Context) int {
	v, err := pugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pugb.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pugb.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pugb *ProfitUnsoldGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pugb *ProfitUnsoldGroupBy) BoolX(ctx context.Context) bool {
	v, err := pugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pugb *ProfitUnsoldGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pugb.fields {
		if !profitunsold.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pugb *ProfitUnsoldGroupBy) sqlQuery() *sql.Selector {
	selector := pugb.sql.Select()
	aggregation := make([]string, 0, len(pugb.fns))
	for _, fn := range pugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pugb.fields)+len(pugb.fns))
		for _, f := range pugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pugb.fields...)...)
}

// ProfitUnsoldSelect is the builder for selecting fields of ProfitUnsold entities.
type ProfitUnsoldSelect struct {
	*ProfitUnsoldQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pus *ProfitUnsoldSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pus.prepareQuery(ctx); err != nil {
		return err
	}
	pus.sql = pus.ProfitUnsoldQuery.sqlQuery(ctx)
	return pus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pus.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) StringsX(ctx context.Context) []string {
	v, err := pus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) StringX(ctx context.Context) string {
	v, err := pus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pus.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) IntsX(ctx context.Context) []int {
	v, err := pus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) IntX(ctx context.Context) int {
	v, err := pus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pus.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) Float64X(ctx context.Context) float64 {
	v, err := pus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pus.fields) > 1 {
		return nil, errors.New("ent: ProfitUnsoldSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) BoolsX(ctx context.Context) []bool {
	v, err := pus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pus *ProfitUnsoldSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{profitunsold.Label}
	default:
		err = fmt.Errorf("ent: ProfitUnsoldSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pus *ProfitUnsoldSelect) BoolX(ctx context.Context) bool {
	v, err := pus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pus *ProfitUnsoldSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pus.sql.Query()
	if err := pus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
