// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProfitDetail is the predicate function for profitdetail builders.
type ProfitDetail func(*sql.Selector)

// ProfitGeneral is the predicate function for profitgeneral builders.
type ProfitGeneral func(*sql.Selector)

// ProfitUnsold is the predicate function for profitunsold builders.
type ProfitUnsold func(*sql.Selector)
