apiVersion: apps/v1
kind: Deployment
metadata:
  name: mining-manager
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mining-manager
  template:
    metadata:
      labels:
        app: mining-manager
    spec:
      containers:
        - name: mining-manager
          image: uhub.service.ucloud.cn/entropypool/mining-manager:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/MiningManager
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: mining-manager-config
            items:
              - key: service-conf
                path: MiningManager.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: mining-manager
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50330
      targetPort: 50330
    - name: grpc
      port: 50331
      targetPort: 50331
    - name: healthz
      port: 50332
      targetPort: 50332
    - name: prometheus
      port: 50333
      targetPort: 50333
  selector:
    app: mining-manager
